
#include <ntddk.h>
#include <wdf.h>

#define KERNELMEMORYIO_TYPE 40000 /* 32768-65535 are reserved for customers */

#define DEVICE_NAME L"\\Device\\KernelMemoryIO"
#define DOS_DEVICE_NAME L"\\DosDevices\\KernelMemoryIO"
#define DEVICE_CLIENT_NAME L"\\\\.\\KernelMemoryIO"

#define IOCTL_READ_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PHYSICAL_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x914, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_WRITE_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GETPOS_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SETPOS_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_READ_PORT_UCHAR \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PORT_USHORT \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x918, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PORT_ULONG \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x928, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_WRITE_PORT_UCHAR \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x909, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PORT_USHORT \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x919, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PORT_ULONG \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x929, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KMIO_TEST \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x100, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct
{
    PUCHAR Position;
} DEVICE_CONTEXT, *PDEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, DeviceGetContext)
