
#define KERNELMEMORYIO_TYPE 40000 /* 32768-65535 are reserved for customers */

#define DEVICE_NAME L"\\Device\\KernelMemoryIO"
#define DOS_DEVICE_NAME L"\\DosDevices\\KernelMemoryIO"
#define DEVICE_CLIENT_NAME L"\\\\.\\KernelMemoryIO"

#define IOCTL_READ_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_WRITE_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GETPOS_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SETPOS_MEMORY \
    CTL_CODE(KERNELMEMORYIO_TYPE, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct 
{ 
    PUCHAR Position;
} MEMORYIO_DEVICE_EXTENSION, * PMEMORYIO_DEVICE_EXTENSION;

